# Copyright (c) 2022 The Orbit Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

name: include-what-you-use
on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/**'

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  iwyu:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-22.04
    timeout-minutes: 180
    steps:
      - name: Checkout Orbit
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          token: '${{ secrets.ORBITPROFILER_BOT_PAT }}'
          path: orbit
      - name: Setup git
        working-directory: ./orbit
        run: |
          git config user.name orbitprofiler-bot
          git config user.email orbitprofiler-bot@google.com
      - name: Check IWYU PR already open
        id: check_has_open_iwyu_pr
        uses: actions/github-script@v6
        with:
          github-token: '${{ secrets.ORBITPROFILER_BOT_PAT }}'
          script: |
            await github.paginate(
                'GET /repos/{owner}/{repo}/pulls{?state,head,base,sort,direction,per_page,page}',
                {
                  owner: owner,
                  repo: repo,
                  state: 'open'
                },
                (response => response.data.some(
                    pr => pr.title === 'Automatically apply IWYU to the codebase'
                        && pr.user.login === 'orbitprofiler-bot'))).then(
                (hasOpenIwyuPr) => {
                  core.setOutput('has_open_iwyu_pr', hasOpenIwyuPr)
                });
      - name: Add llvm-15 repo
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        run: |
          sudo bash -c 'echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-15 main" >> /etc/apt/sources.list'
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
      - name: Install dependencies
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        run: |
           sudo apt-get update &&                             \
           sudo apt-get install --yes --no-install-recommends \
           build-essential                                    \
           cmake                                              \
           ccache                                             \
           libboost-dev                                       \
           libcapstone-dev                                    \
           libgrpc++-dev                                      \
           libssh2-1-dev                                      \
           vulkan-validationlayers-dev                        \
           libz-dev                                           \
           llvm-dev                                           \
           protobuf-compiler-grpc                             \
           pkg-config                                         \
           libvulkan-volk-dev                                 \
           libvulkan-dev                                      \
           libopengl-dev                                      \
           libglx-dev                                         \
           mesa-common-dev                                    \
           qtbase5-dev                                        \
           libgtest-dev                                       \
           libgmock-dev                                       \
           git                                                \
           ninja-build                                        \
           clang-format-14                                    \
           llvm-15-dev                                        \
           libclang-15-dev                                    \
           clang-15                                           \
           patchutils                                         \
           libprotobuf-dev
      - name: Checkout IWYU
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        uses: actions/checkout@v3
        with:
          repository: include-what-you-use/include-what-you-use
          ref: 7f0b6c304acf69c42bb7f6e03c63f836924cb7e0 # clang_15 @ Nov 2, 2022
          path: iwyu
      - run: mkdir build
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        working-directory: ./iwyu
      - name: Configure IWYU
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        working-directory: ./iwyu/build
        run: |
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=/usr/lib/llvm-15 -DCMAKE_INSTALL_PREFIX=/usr "${GITHUB_WORKSPACE}/iwyu"
      - name: Build and install IWYU
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        working-directory: ./iwyu/build
        run: sudo cmake --build "${GITHUB_WORKSPACE}/iwyu/build" --target install
      - run: mkdir build
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        working-directory: ./orbit
      - name: CMake Configure
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        working-directory: ./orbit/build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release                                                             \
           -DCMAKE_CXX_FLAGS="-march=sandybridge -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer" \
           "${GITHUB_WORKSPACE}/orbit"
      - name: CMake Build
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        working-directory: ./orbit/build
        run: cmake --build . --target iwyu
      - name: Export branch name
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        run: |
          export IWYU_CLEANUP_BRANCH="cleanup/iwyu-${GITHUB_SHA}"
          echo "IWYU_CLEANUP_BRANCH=${IWYU_CLEANUP_BRANCH}" >> $GITHUB_ENV
      - name: Try to apply changes
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        working-directory: ./orbit
        run: |
          git checkout -b ${{ env.IWYU_CLEANUP_BRANCH }}
          git update-index --refresh
          git apply --index build/iwyu.diff
      - name: Check for changes
        if: steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        working-directory: ./orbit
        id: check_changes
        run: |
          if git diff --cached --exit-code >/dev/null; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Apply and push changes
        if: steps.check_changes.outputs.has_changes == 'true' &&
            steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        working-directory: ./orbit
        run: |
          git commit --message="Automatically apply IWYU to the codebase"
          git push --set-upstream origin ${{ env.IWYU_CLEANUP_BRANCH }}
      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true' &&
            steps.check_has_open_iwyu_pr.outputs.has_open_iwyu_pr == 'false'
        uses: actions/github-script@v6
        with:
          github-token: '${{ secrets.ORBITPROFILER_BOT_PAT }}'
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Automatically apply IWYU to the codebase',
              owner,
              repo,
              head: process.env.IWYU_CLEANUP_BRANCH,
              base: 'main',
              body: [
                'This is an automatically generated pull request.',
                'Review the changes carefully and merge the pull request after approval.',
                'The changes are based on commit ' + context.sha + '.',
                '\n',
                'Please delete the branch after merging the pull request.'
              ].join('\n')
            });
